# Generated by Django 5.1 on 2024-08-12 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 8, 12, 17, 53, 19, 826734, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
