# Generated by Django 5.1 on 2024-08-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_transactions_date_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cards',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Detailed_desc',
        ),
        migrations.DeleteModel(
            name='NetBanking',
        ),
        migrations.DeleteModel(
            name='pessanger_detail',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
